from pathlib import Path
import sys
import csv
import json

import torch
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from models.resnet18_extractor import ResNet18Extractor
from evaluate_triplet import (
    CLASS_NAMES,
    QUERY_DIR,
    RESULTS_DIR,
    CHECKPOINT,
    TRANSFORM,
    ImagePathDataset,
    extract_features,
)

BASELINE_GALLERY = RESULTS_DIR / "gallery_resnet18.pt"
TRIPLET_GALLERY = RESULTS_DIR / "gallery_resnet18_triplet.pt"
BATCH_SIZE = 128
NUM_WORKERS = 4


def get_query_data():
    paths, labels = [], []
    for class_id, class_name in enumerate(CLASS_NAMES):
        class_paths = sorted((QUERY_DIR / class_name).glob("*.png"))
        paths.extend(str(p) for p in class_paths)
        labels.extend([class_id] * len(class_paths))
    return paths, torch.tensor(labels, dtype=torch.long)


def evaluate_by_class(query_features, query_labels,
                      gallery_features, gallery_labels):
    similarities = query_features @ gallery_features.T
    top_indices = similarities.topk(10, dim=1).indices
    top_labels = gallery_labels[top_indices]

    result = {}
    for class_id, class_name in enumerate(CLASS_NAMES):
        mask = query_labels == class_id
        result[class_name] = {}

        for k in (1, 5, 10):
            hits = (
                top_labels[mask, :k] == query_labels[mask, None]
            ).any(dim=1)
            result[class_name][f"HitRate@{k}"] = hits.float().mean().item()

    return result


def load_baseline_model(device):
    # The original gallery was generated by the pretrained ImageNet model.
    model = ResNet18Extractor(pretrained=True).to(device)
    model.eval()
    return model


def load_triplet_model(device):
    checkpoint = torch.load(
        CHECKPOINT, map_location="cpu", weights_only=True
    )
    model = ResNet18Extractor(pretrained=False)
    model.load_state_dict(checkpoint["model_state_dict"], strict=True)
    model = model.to(device)
    model.eval()
    print(
        f"Triplet checkpoint: epoch={checkpoint['epoch']}, "
        f"val_loss={checkpoint['val_loss']:.6f}"
    )
    return model


def main():
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print("Device:", device)

    query_paths, query_labels = get_query_data()
    print("Query images:", len(query_paths))

    baseline_gallery = torch.load(
        BASELINE_GALLERY, map_location="cpu", weights_only=False
    )
    triplet_gallery = torch.load(
        TRIPLET_GALLERY, map_location="cpu", weights_only=False
    )

    # Check that gallery labels and ordering agree with query class IDs.
    baseline_labels = baseline_gallery["labels"].long()
    triplet_labels = triplet_gallery["labels"].long()

    print("\nExtracting Baseline Query features...")
    baseline_model = load_baseline_model(device)
    baseline_query_features = extract_features(
        baseline_model, query_paths, query_labels, device
    )
    del baseline_model
    if device.type == "cuda":
        torch.cuda.empty_cache()

    print("\nExtracting Triplet Query features...")
    triplet_model = load_triplet_model(device)
    triplet_query_features = extract_features(
        triplet_model, query_paths, query_labels, device
    )
    del triplet_model
    if device.type == "cuda":
        torch.cuda.empty_cache()

    baseline_results = evaluate_by_class(
        baseline_query_features, query_labels,
        baseline_gallery["features"].float(), baseline_labels
    )
    triplet_results = evaluate_by_class(
        triplet_query_features, query_labels,
        triplet_gallery["features"].float(), triplet_labels
    )

    output_json = {}
    csv_path = RESULTS_DIR / "class_metrics_comparison.csv"

    with open(csv_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "class", "metric", "baseline", "triplet",
            "delta_percentage_points"
        ])

        print("\n===== Per-class Hit Rate Comparison =====")
        for class_name in CLASS_NAMES:
            output_json[class_name] = {}
            for k in (1, 5, 10):
                metric = f"HitRate@{k}"
                before = baseline_results[class_name][metric]
                after = triplet_results[class_name][metric]
                delta = (after - before) * 100

                output_json[class_name][metric] = {
                    "baseline": before,
                    "triplet": after,
                    "delta_percentage_points": delta,
                }
                writer.writerow([
                    class_name, metric, f"{before:.4f}",
                    f"{after:.4f}", f"{delta:+.2f}"
                ])

                print(
                    f"{class_name:10s} {metric:9s} "
                    f"Baseline={before * 100:6.2f}%  "
                    f"Triplet={after * 100:6.2f}%  "
                    f"Delta={delta:+6.2f} pp"
                )

    json_path = RESULTS_DIR / "class_metrics_comparison.json"
    with open(json_path, "w") as f:
        json.dump(output_json, f, indent=2)

    # Plot all classes for Hit Rate@1, the most selective metric.
    x = list(range(len(CLASS_NAMES)))
    width = 0.36
    base_values = [
        baseline_results[c]["HitRate@1"] * 100 for c in CLASS_NAMES
    ]
    triplet_values = [
        triplet_results[c]["HitRate@1"] * 100 for c in CLASS_NAMES
    ]

    fig, ax = plt.subplots(figsize=(12, 6))
    ax.bar([i - width / 2 for i in x], base_values,
           width, label="Baseline")
    ax.bar([i + width / 2 for i in x], triplet_values,
           width, label="Triplet Loss")
    ax.set_ylabel("Hit Rate@1 (%)")
    ax.set_title("Per-class Image Retrieval: Baseline vs Triplet Loss")
    ax.set_xticks(x)
    ax.set_xticklabels(CLASS_NAMES, rotation=30, ha="right")
    ax.set_ylim(0, 100)
    ax.legend()
    ax.grid(axis="y", alpha=0.25)
    fig.tight_layout()

    plot_path = RESULTS_DIR / "class_hit_rate_at1.png"
    fig.savefig(plot_path, dpi=160, bbox_inches="tight")
    plt.close(fig)

    print("\nSaved CSV:", csv_path)
    print("Saved JSON:", json_path)
    print("Saved plot:", plot_path)
    print("Per-class analysis: PASS")


if __name__ == "__main__":
    main()
